### ISSUE TITLE
Resource busy

### ISSUE THREAD

**Issue by arunmagesh** [Xipiter/shikra-programmer#2]
Why am i getting this?

shikra> find_shikra
[+] Looking for Shikra...
[+] Shikra device found.
Traceback (most recent call last):
  File "./shikra.py", line 566, in <module>
    shell.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "./shikra.py", line 78, in do_find_shikra
    SHIKRA.config()
  File "./shikra.py", line 240, in config
    self.shikra_dev.set_configuration()
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 554, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 92, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 503, in set_configuration
    _check(_lib.libusb_set_configuration(dev_handle, config_value))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 403, in _check
    raise USBError(_str_error[ret], ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy

When open'd using FT_PROG EEPROM was empty.

**Comment by hamid-elaosta** [comment]
You need to `rmmod ftdi_sio`

See this PR https://github.com/Xipiter/shikra-programmer/pull/1

**Comment by linker3000** [comment]
If you want to keep the ftdi_sio module loaded for other purposes, you just need to modify the Shikra-programmer program to free the FT232H. Change the code around line 238 as below:

```
def config(self):
        # set first active
        '''     
        Linker3000: Free the FT232H if it's already been claimed...
        '''     
        if self.shikra_dev.is_kernel_driver_active(0):
            reattach = True
            self.shikra_dev.detach_kernel_driver(0)
        self.shikra_dev.set_configuration()
```
